// <auto-generated />
using System;
using Covid19.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Covid19.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Covid19.Server.Models.CovidConfirmedCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Confirmed")
                        .HasColumnType("integer");

                    b.Property<string>("CountryRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("ProvinceState")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CovidConfirmedCases");
                });

            modelBuilder.Entity("Covid19.Server.Models.CovidDailyReport", b =>
                {
                    b.Property<double>("UID")
                        .HasColumnType("double precision");

                    b.Property<double?>("Active")
                        .HasColumnType("double precision");

                    b.Property<double?>("CaseFatalityRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("Confirmed")
                        .HasColumnType("double precision");

                    b.Property<string>("CountryRegion")
                        .HasColumnType("text");

                    b.Property<double?>("Deaths")
                        .HasColumnType("double precision");

                    b.Property<double?>("FIPS")
                        .HasColumnType("double precision");

                    b.Property<string>("ISO3")
                        .HasColumnType("text");

                    b.Property<double?>("IncidentRate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("ProvinceState")
                        .HasColumnType("text");

                    b.Property<double?>("Recovered")
                        .HasColumnType("double precision");

                    b.HasKey("UID");

                    b.ToTable("CovidDailyReports");
                });

            modelBuilder.Entity("Covid19.Server.Models.CovidDataPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Confirmed")
                        .HasColumnType("integer");

                    b.Property<string>("CountryRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("ProvinceState")
                        .HasColumnType("text");

                    b.Property<int>("Recovered")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CovidDataPoints");
                });

            modelBuilder.Entity("Covid19.Server.Models.CovidDeathCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("ProvinceState")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CovidDeathCases");
                });

            modelBuilder.Entity("Covid19.Server.Models.CovidRecoverCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("ProvinceState")
                        .HasColumnType("text");

                    b.Property<int>("Recovered")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CovidRecoverCases");
                });
#pragma warning restore 612, 618
        }
    }
}
